# ML for Phys: Lecture 2 exercises

In [1]:
import numpy as np
import pandas as ps
import matplotlib.pyplot as plt

In [45]:
def eval_layer(y, w, b):
    #wexp = np.array([w]*len(y))
    z = np.dot(w, y.T).T + b
    return 1.0/(1.0 + np.exp(-10*z))

def contour_plot(x_list, y_list, ):

    xlist = np.linspace(-3.0, 3.0, 100)
    ylist = np.linspace(-3.0, 3.0, 100)
    X, Y = np.meshgrid(xlist, ylist)
    Z = np.sqrt(X**2 + Y**2)
    fig,ax=plt.subplots(1,1)
    cp = ax.contourf(X, Y, Z)
    fig.colorbar(cp) # Add a colorbar to a plot
    ax.set_title('Filled Contours Plot')
    #ax.set_xlabel('x (cm)')
    ax.set_ylabel('y (cm)')
    plt.show()

### Logic gates with neural nets

#### AND gate

Inputs $y1$, $y2$ are combined to find $z$

$$z = y1 + y2 - 1.5$$

In [50]:
w = np.array([1,1])
b = np.array([-1.5])

y = np.array([[0,0],[0,1], [1,0], [1,1]])

eval_layer(y, w, b)

array([3.05902227e-07, 6.69285092e-03, 6.69285092e-03, 9.93307149e-01])

#### OR gate

Inputs $y1$, $y2$ are combined to find $z$

$$ z = y1 + y2 - 0.5 $$

In [49]:
w = np.array([1,1])
b = np.array([-0.5])

y = np.array([[0,0],[0,1], [1,0], [1,1]])

eval_layer(y, w, b)

array([0.00669285, 0.99330715, 0.99330715, 0.99999969])

#### XOR gate

Inputs $y^0_1$, $y^0_1$ are combined to find $z^1_1$ as AND gate and $z^1_2$ as OR gate. These in turn are combined to find $z^2_1$ as AND gate.

$$z^1_1 = y^0_1 + y^0_2 - 1.5, z^1_2 = y^0_1 + y^0_2 - 0.5, z3 = y^1_1 + y^1_2 - 1.5$$


In [48]:
w1 = np.array([[1,1], [1,1]])
b1 = np.array([-1.5, -0.5])

w2 = np.array([-1,1])
b2 = np.array([-0.5])


y0 = np.array([[0,0],[0,1], [1,0], [1,1]])
print(y0)
y1 = eval_layer(y0, w1, b1)
print(y1)
y2 = eval_layer(y1, w2, b2)
print(y2)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[3.05902227e-07 6.69285092e-03]
 [6.69285092e-03 9.93307149e-01]
 [6.69285092e-03 9.93307149e-01]
 [9.93307149e-01 9.99999694e-01]]
[0.00715279 0.99235586 0.99235586 0.00715279]


### Draw figures in the plane $(y^0_1, y^0_2)$

In [51]:
w1 = np.array([[1,0], [0,1]])
b1 = np.array([-1.5, -0.5])

w2 = np.array([[-1,0], [0,-1]])
b2 = np.array([3.5, 4.5])

w3 = np.array([1,1])
b3 = np.array([-1.5])

y0 = np.array([[0,0],[2.5, 5.0], [4.0, 3.0], [2.5,3.0]])
print(y0)
y1 = eval_layer(y0, w1, b1)
print(y1)
y2 = eval_layer(y1, w2, b2)
print(y2)
y3 = eval_layer(y2, w3, b3)
print(y3)

[[0.  0. ]
 [2.5 5. ]
 [4.  3. ]
 [2.5 3. ]]
[[3.05902227e-07 6.69285092e-03]
 [9.99954602e-01 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00]
 [9.99954602e-01 1.00000000e+00]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[0.99330715 0.99330715 0.99330715 0.99330715]
